language: node_js
node_js:
<<<<<<< HEAD
  - '6.9'
  - '7.7'
cache:
  yarn: true
  directories:
    - node_modules
before_script:
  - yarn
script:
  - yarn test
=======
  - "6"
  - "4"
  - "0.12"
  - "0.10"
>>>>>>> Update supported node engines to 0.10+
